# Generated by Django 4.0.4 on 2022-05-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_season_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(allow_unicode=True, auto_created=True, blank=True),
        ),
    ]
