# Generated by Django 4.0.4 on 2022-05-29 10:25

import authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.managers.UserManager()),
            ],
        ),
    ]
